// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqytgeaomrrshxqeibxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxeXRnZWFvbXJyc2h4cWVpYnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTY4MzksImV4cCI6MjA2OTE5MjgzOX0.IXVhrFga5O3tqA40-S6Gk1Ce5o5G28dqwm1iMKb15KE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});